# Generated by Django 5.0.1 on 2024-01-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='actividad',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
